boxes = [
{
    :name => "img",
    :ip => "10.168.123.11",
    :ip2 => "10.1.2.3",
    :ssh_port => "2203",
    :bootstrap => "img_bootstrap.sh",
    :memory => "5120",
    :cpus => "4"
},
{
    :name => "devstack",
    :ip => "10.168.123.10",
    :ip2 => "10.1.2.3",
    :ssh_port => "2202",
    :bootstrap => "dvstk_bootstrap.sh",
    :memory => "10240",
    :cpus => "4"
},
{
    :name => "minikube",
    :ip => "10.168.123.9",
    :ip2 => "10.1.2.3",
    :ssh_port => "2201",
    :bootstrap => "mkb_bootstrap.sh",
    :memory => "5120",
    :cpus => "2"
},
]

Vagrant.configure('2') do |config|
boxes.each do |opts|
  config.vm.box = "generic/ubuntu1804"

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false  
end

  config.vm.define opts[:name] do |config|
    config.vm.hostname = opts[:name]
    config.vm.network :private_network, ip: opts[:ip]
    config.vm.network :private_network, ip: opts[:ip2], auto_config: false
#    config.vm.network :forwarded_port, guest: 22, guest_ip: opts[:ip], host: opts[:ssh_port], id: 'ssh'
    config.vm.provision "shell", inline: <<-SHELL
      sed -i "/127.0.1.1/d" /etc/hosts
      echo "10.168.123.9 minikube" >> /etc/hosts
      echo "10.168.123.10 devstack" >> /etc/hosts
     echo "10.168.123.11 img" >> /etc/hosts
    SHELL
    config.vm.provision "shell", inline: 'ip l set eth2 up; ip a flush eth2; dhclient eth2; ip r del default via 10.0.2.2 dev eth0'
    config.vm.provision "shell", path: opts[:bootstrap], keep_color: true
   config.vm.provider "virtualbox" do |vb|
     vb.gui = false
     vb.memory = opts[:memory]
     vb.cpus = opts[:cpus]
     vb.customize ["modifyvm", :id, "--nic3", "natnetwork", "--nat-network3", "5gnat"]
    end
  end
end
end
